[WIP] A simple tutorial for building ASR system
k2-fsa/next-gen-kaldi-wechat pull request #2
Opened 2022-06-28 13:13 UTC by luomingshuang

2022-06-28 15:19 UTC, csukuangfj commented
很厉害呀！！！

2022-06-29 13:39 UTC, csukuangfj requested changes

2022-06-30 02:40 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +>本文将介绍如何基于新一代 Kaldi 框架快速搭建一个服务端的ASR系统，包括数据准备、构建recipe训练测试、服务端部署运行。
```suggestion
>本文将介绍如何基于新一代 Kaldi 框架快速搭建一个服务端的ASR系统，包括数据准备、构建 recipe 训练测试、服务端部署运行。
```

英文单词的前后，都要加一个空格。

请检查全文，不要只改 Kaldi 这一处。

2022-06-30 02:54 UTC, csukuangfj requested changes

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +距离新一代Kaldi开源框架的正式发布已经有一段时间了，截止目前，框架基本的四梁八柱都已经立起来了。那么，如何用它快速搭建ASR系统呢？
```suggestion
距离新一代 Kaldi 开源框架的正式发布已经有一段时间了。截止目前，框架基本的四梁八柱都已经立起来了。那么，如何用它快速搭建 ASR 系统呢？
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +阅读过前面几期公众文的读者可能都知道新一代Kaldi框架主要包含了四个不同的子项目：k2、icefall、lhotse、sherpa，其中，k2是核心算法库，icefall是数据集训练测试示例脚本，lhotse是语音数据处理工具集，sherpa是服务端框架，四个子项目共同构成了新一代Kaldi框架。另一方面，截止目前，新一代kaldi框架在很多公开数据集上都获得了很有竞争力的识别结果，在Wene
```suggestion
阅读过前面几期公众文的读者可能都知道新一代 Kaldi 框架主要包含了四个不同的子项目：k2、icefall、lhotse 和 sherpa。其中，k2 是核心算法库，icefall 是数据集训练测试示例脚本，lhotse 是语音数据处理工具集，sherpa 是服务端框架。四个子项目共同构成了新一代 Kaldi 框架。另一方面，截止目前，新一代 Kaldi 框架在很多公开数据集上都获得了很有竞争力的识别结果，在 WenetSpeech 和 GigaSpeech 上甚至都获得了 SOTA 的性能。

看到这，相信很多小伙伴都已经摩拳擦掌、跃跃欲试了。本文的目标就是试图贯通新一代 Kaldi 的四个子项目，为快速搭建一个服务端的 ASR 系统提供一个简易的教程。

希望看完本文的小伙伴都能顺利搭建出自己的 ASR 系统。
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +本文主要介绍如何从原始数据下载处理、模型训练测试、到得到一个服务端ASR系统的过程，根据功能，分为三步：`数据准备和处理`、`模型训练和测试`、`服务端部署演示`。
```suggestion
本文主要介绍如何从原始数据下载处理、模型训练测试、到得到一个服务端 ASR 系统的过程。根据功能，分为三步：

- 数据准备和处理
- 模型训练和测试
- 服务端部署演示
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +(注：本文介绍的ASR系统是基于RNN-T的框架且不涉及外加的语言模型，所以，本文将不涉及WFST等语言模型的内容，如后期有需要，会在后面的文章中另行讲述。)
```suggestion
> 本文介绍的 ASR 系统是基于 RNN-T 框架且不涉及外加的语言模型。所以，本文将不涉及 WFST 等语言模型的内容。如后期有需要，会在后面的文章中另行讲述。
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +为了更加形象、具体地描述这个过程，本文以构建一个基于WenetSpeech数据集的[pruned transducer stateless2 recipe](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe")为例，希望尽可能为读者详细地描
```suggestion
为了更加形象、具体地描述这个过程，本文以构建一个基于 WenetSpeech 数据集的[pruned transducer stateless2 recipe](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe")为例，希望尽可能为读者详细地描述这一过程，也希望读者能够在本文的基础上能够无障碍地迁移到其他数据集的处理、训练和部署使用上去。
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +(注：本文描述的过程和展示的代码更多的是为了描述功能，而非详细的实现过程，详细的实现代码请读者自行参考[egs/wenetspeech/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe"), 另外，使用者应该事先安装好k2、ice
```suggestion
> 本文描述的过程和展示的代码更多的是为了描述功能，而非详细的实现过程。详细的实现代码请读者自行参考[egs/wenetspeech/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe")。另外，使用者应该事先安装好 k2、icefall、lhotse 和 sherpa
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +(注：在这里我们也用了musan对数据进行增广，具体的可以参考prepare.sh中对musan处理和使用的相关指令，这里不针对介绍。)
```suggestion
> 在这里我们也用了 musan 对数据进行增广，具体的可以参考prepare.sh 中对 musan 处理和使用的相关指令，这里不针对介绍。
```

可以对 musan 加个超链接

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +为了统一文件名，这里将数据包文件名变为WenetSpeech, 其中audio包含了所有训练和测试的数据
```suggestion
为了统一文件名，这里将数据包文件名变为 WenetSpeech，其中 audio 包含了所有训练和测试的数据
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +```
```suggestion
```bash
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +查看WenetSpeech.json文件，部分信息如下所示，WenetSpeech.json中包含了音频文件路径和相关的监督信息：
```suggestion
查看 `WenetSpeech.json` 文件，部分信息如下所示。`WenetSpeech.json` 中包含了音频文件路径和相关的监督信息：
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +```
```suggestion
```json
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +(注：WenetSpeech中文数据集中包含了S，M，L三个不同规模的训练数据集)
```suggestion
(注：WenetSpeech 中文数据集中包含了 S，M 和 L 三个不同规模的训练数据集)
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +```
```suggestion
```bash
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +关于lhotse是如何将原始数据处理成jsonl.gz格式文件的，这里可以参考文件[wenet_speech.py](https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/wenet_speech.py, "wenet_speech.py")， 其主要功能是生成recordings和supervisions的json
```suggestion
关于 lhotse 是如何将原始数据处理成 `jsonl.gz` 格式文件的，可以参考文件 [wenet_speech.py](https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/wenet_speech.py, "wenet_speech.py")， 其主要功能是生成 `recordings` 和 `supervisions` 的 `jsonl.gz` 格式文件
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +这里，可用vim对recordings和supervisions的jsonl.gz文件进行查看, 其中：
```suggestion
这里，可用 `vim` 对 `recordings` 和 `supervisions` 的 `jsonl.gz` 文件进行查看, 其中：
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +```
```suggestion
```bash
```

2022-06-30 02:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +```
```suggestion
```bash
```

2022-07-01 04:25 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +>本文将介绍如何基于新一代Kaldi框架快速搭建一个服务端的ASR系统，包括数据准备、构建recipe训练测试、服务端部署运行。
请再检查下全文

2022-07-01 06:42 UTC, luomingshuang commented
Thanks.

2022-07-01 07:10 UTC, yaozengwei commented on 2022-06-31-build-asr-system-tutorial.md
> +对于数据准备和处理部分，所有的运行指令都集成在文件 [prepare.sh](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/prepare.sh "prepare.sh")中，主要的作用可以总结为两个：`准备音频文件并进行特征提取`、`构建语言建模文件`。
```suggestion
对于数据准备和处理部分，所有的运行指令都集成在文件 [prepare.sh](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/prepare.sh "prepare.sh") 中，主要的作用可以总结为两个：`准备音频文件并进行特征提取`、`构建语言建模文件`。
```

2022-07-01 07:12 UTC, yaozengwei commented on 2022-06-31-build-asr-system-tutorial.md
> +我们选择`Offline-Record`，并打开麦克风，即可录音识别了。笔者的一个识别结果如下图所示：
```suggestion
我们选择 `Offline-Record`，并打开麦克风，即可录音识别了。笔者的一个识别结果如下图所示：
```

2022-07-01 07:15 UTC, yaozengwei commented on 2022-06-31-build-asr-system-tutorial.md
> +# 如何基于新一代 Kaldi 框架快速搭建服务端ASR系统
```suggestion
# 如何基于新一代 Kaldi 框架快速搭建服务端 ASR 系统
```

2022-07-01 07:28 UTC, luomingshuang commented
Thanks.

2022-07-01 08:13 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +另一方面，截止目前，新一代 kaldi 框架在很多公开数据集上都获得了很有竞争力的识别结果，在 WenetSpeech 和 GigaSpeech 上甚至都获得了SOTA的性能。
```suggestion
另一方面，截止目前，新一代 Kaldi 框架在很多公开数据集上都获得了很有竞争力的识别结果，在 WenetSpeech 和 GigaSpeech 上甚至都获得了 SOTA 的性能。
```

再检查一下全文。英文单词的前后，都加一个空格.

是 Kaldi, 不是 kaldi. 全文要统一。

请再检查一下

2022-07-01 08:18 UTC, luomingshuang commented on 2022-06-31-build-asr-system-tutorial.md
> +另一方面，截止目前，新一代 kaldi 框架在很多公开数据集上都获得了很有竞争力的识别结果，在 WenetSpeech 和 GigaSpeech 上甚至都获得了SOTA的性能。
Thanks.

2022-07-01 08:36 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +本文介绍的 ASR 系统是基于 RNN-T 的框架且不涉及外加的语言模型，所以，本文将不涉及 WFST 等语言模型的内容，如后期有需要，会在后面的文章中另行讲述。
```suggestion
本文介绍的 ASR 系统是基于 RNN-T 框架且不涉及外加的语言模型，所以，本文将不涉及 WFST 等语言模型的内容，如后期有需要，会在后面的文章中另行讲述。
```

去掉的

2022-07-01 08:53 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +另一方面，截止目前，新一代 Kaldi 框架在很多公开数据集上都获得了很有竞争力的识别结果，在 WenetSpeech 和 GigaSpeech 上甚至都获得了SOTA的性能。
```suggestion
另一方面，截止目前，新一代 Kaldi 框架在很多公开数据集上都获得了很有竞争力的识别结果，在 WenetSpeech 和 GigaSpeech 上甚至都获得了 SOTA 的性能。
```

再检查一遍呀

2022-07-01 08:54 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +本文介绍的 ASR 系统是基于 RNN-T 框架且不涉及外加的语言模型，所以，本文将不涉及 WFST 等语言模型的内容，如后期有需要，会在后面的文章中另行讲述。
```suggestion
本文介绍的 ASR 系统是基于 RNN-T 框架且不涉及外加的语言模型。所以，本文将不涉及 WFST 等语言模型的内容，如后期有需要，会在后面的文章中另行讲述。
```

2022-07-01 08:55 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +为了更加形象、具体地描述这个过程，本文以构建一个基于 WenetSpeech 数据集的 [pruned transducer stateless2 recipe](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe") 为例，希望尽可能为读者
构建一个基于 xxx 数据集的 xx 为例

这句话不通顺。请改一下

2022-07-01 08:57 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +本文描述的过程和展示的代码更多的是为了描述功能，而非详细的实现过程，详细的实现代码请读者自行参考 [egs/wenetspeech/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe")。
```suggestion
本文描述的过程和展示的代码更多的是为了描述功能，而非详细的实现过程，详细的实现代码请读者自行参考 [egs/wenetspeech/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR "pruned transducer stateless2 recipe")。
```

请点一下这个文章里面，所有的 hyperlinks. 你上面这个，就不行.

你自己去 https://github.com/luomingshuang/next-gen-kaldi-wechat/blob/build-asr-system-tutorial/2022-06-31-build-asr-system-tutorial.md

去点

2022-07-01 08:57 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +本文描述的过程和展示的代码更多的是为了描述功能，而非详细的实现过程，详细的实现代码请读者自行参考 [egs/wenetspeech/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe")。
```suggestion
本文描述的过程和展示的代码更多的是为了描述功能，而非详细的实现过程，详细的实现代码请读者自行参考 [egs/wenetspeech/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR "pruned transducer stateless2 recipe")。
```

请点一下这个文章里面，所有的 hyperlinks. 你上面这个，就不行.

你自己去 https://github.com/luomingshuang/next-gen-kaldi-wechat/blob/build-asr-system-tutorial/2022-06-31-build-asr-system-tutorial.md

去点

2022-07-01 08:58 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +**Note**: 使用者应该事先安装好 k2、icefall、lhotse、sherpa，这里我们建议读者使用`python3 setup.py install`来安装 k2 。
```suggestion
**Note**: 使用者应该事先安装好 `k2`、icefall、lhotse、sherpa，这里我们建议读者使用`python3 setup.py install`来安装 k2 。
```

用 "``" 把 k2, icefall, lhotse 等，括起来.

2022-07-01 08:59 UTC, luomingshuang commented on 2022-06-31-build-asr-system-tutorial.md
> +为了更加形象、具体地描述这个过程，本文以构建一个基于 WenetSpeech 数据集的 [pruned transducer stateless2 recipe](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe") 为例，希望尽可能为读者
本文以构建一个基于 WenetSpeech 数据集训练的 [pruned transducer stateless2](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2") recipe 为例, 这样？

2022-07-01 08:59 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +**Note**: 使用者应该事先安装好 k2、icefall、lhotse、sherpa，这里我们建议读者使用`python3 setup.py install`来安装 k2 。
为什么要用这个建议呢。

建议删掉这个建议

2022-07-01 09:00 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +对于数据准备和处理部分，所有的运行指令都集成在文件 [prepare.sh](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/prepare.sh "prepare.sh") 中，主要的作用可以总结为两个：`准备音频文件并进行特征提取`、`构建语言建模文件`。
```suggestion
对于数据准备和处理部分，所有的运行指令都集成在文件 [prepare.sh](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/prepare.sh) 中，主要的作用可以总结为两个：`准备音频文件并进行特征提取`、`构建语言建模文件`。
```

为什么后面要加一个 `"prepare.sh"`?

2022-07-01 09:00 UTC, luomingshuang commented on 2022-06-31-build-asr-system-tutorial.md
> +本文描述的过程和展示的代码更多的是为了描述功能，而非详细的实现过程，详细的实现代码请读者自行参考 [egs/wenetspeech/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR, "pruned transducer stateless2 recipe")。
雀实...

2022-07-01 09:00 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +（注：在这里我们也用了 musan 数据集对训练数据进行增广，具体的可以参考 prepare.sh 中对 musan 处理和使用的相关指令，这里不针对介绍。）
这个 prepare.sh, 请给它加一个超链接。

2022-07-01 09:02 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +> - 下载并解压数据
```suggestion
#####  下载并解压数据
```

2022-07-01 09:07 UTC, luomingshuang commented
<img width="367" alt="8961f850dca3840c7792204a6aa6e26" src="https://user-images.githubusercontent.com/37799481/176863452-e6eea43c-3604-4303-953f-c8f9dc610467.png">

“为什么后面要加一个 "prepare.sh"?”
>为了在公众文当中显示如上图的效果

2022-07-01 09:08 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +首先，对数据进行预处理，包括对文本进行标准化和对音频进行时域上的增广，可参考文件 [preprocess_wenetspeech.py](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/local/preprocess_wenetspeech.py, "preprocess_wenetspeech.py")。
```suggestion
首先，对数据进行预处理，包括对文本进行标准化和对音频进行时域上的增广，可参考文件 [preprocess_wenetspeech.py](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/local/preprocess_wenetspeech.py)。
```

2022-07-01 09:10 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +其次，将数据集切片并对每个切片数据集进行特征提取，可参考文件  [compute_fbank_wenetspeech_splits.py](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_splits.py, "compute_fbank_wenet
```suggestion
其次，将数据集切片，并对每个切片数据集进行特征提取。可参考文件  [compute_fbank_wenetspeech_splits.py](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/local/compute_fbank_wenetspeech_splits.py)。
```

2022-07-01 09:11 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +（注：这里的切片是为了可以开启多个进程同时对大规模数据集进行特征提取，提高效率，如果数据集比较小，对数据进行切片处理不是必须的。）
```suggestion
（注：这里的切片是为了可以开启多个进程同时对大规模数据集进行特征提取，提高效率。如果数据集比较小，对数据进行切片处理不是必须的。）
```

注意加句号。不要一口气，把这么长的一个句子一次性读完。

2022-07-01 09:11 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +## 这里的 L 也可修改为 M 或 S, 表示训练数据子集
```suggestion
# 这里的 L 也可修改为 M 或 S, 表示训练数据子集
```

2022-07-01 09:13 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +在 `RNN-T` 的模型框架中，我们实际需要的用于训练和测试的建模文件有 `tokens.txt`、`words.txt` 和 `Linv.pt` 。 我们按照如下步骤构建语言建模文件：
```suggestion
在 `RNN-T` 模型框架中，我们实际需要的用于训练和测试的建模文件有 `tokens.txt`、`words.txt` 和 `Linv.pt` 。 我们按照如下步骤构建语言建模文件：
```

2022-07-01 09:13 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +#### 构建语言建模文件
这个不叫语言模型文件吧？

2022-07-01 09:14 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +在这一步骤中，规范文本的函数文件可参考 [text2token.py](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/local/text2token.py, "text2token.py")。
```suggestion
在这一步骤中，规范文本的函数文件可参考 [text2token.py](https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/local/text2token.py)。
```

2022-07-01 09:18 UTC, csukuangfj commented on 2022-06-31-build-asr-system-tutorial.md
> +#### 构建语言建模文件
我看错了，请忽略上面一条评论

2022-07-01 09:20 UTC, luomingshuang commented on 2022-06-31-build-asr-system-tutorial.md
> +#### 构建语言建模文件
额，那应该叫啥，我不是很确定，文本建模文件？

2022-07-01 09:30 UTC, luomingshuang commented
Done. Thanks.

2022-07-01 09:40 UTC, csukuangfj commented on 2022-06-31-a-simple-tutorial-about-building-asr-system.md
> +本文描述的过程和展示的代码更多的是为了描述功能，而非详细的实现过程，详细的实现代码请读者自行参考 [egs/wenetspeech/ASR](https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/ASR "pruned transducer stateless2 recipe")。
而非详细的实现过程

后面用句号

2022-07-01 09:45 UTC, csukuangfj commented on 2022-06-31-a-simple-tutorial-about-building-asr-system.md
> +最后，待提取完每个切片数据集的特征，将所有切片数据集的特征数据合并成一个总的特征数据集：
待提取xxx后，


加个后字

2022-07-01 09:49 UTC, csukuangfj commented on 2022-06-31-a-simple-tutorial-about-building-asr-system.md
> +至此，第一步全部完成。对于不同数据集来说，其基本思路也是类似的，在数据准备和处理阶段，我们主要做两件事情：`准备音频文件并进行特征提取`、`构建语言建模文件`。
类似的。后面的逗号改成句号

2022-07-01 10:16 UTC, luomingshuang commented
Thanks.

2022-07-01 15:15 UTC, luomingshuang commented
Thanks for your suggestions.

2022-07-01 15:16 UTC, merged